version: "3"

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mariadb:10.10
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: bloggy
      MYSQL_USER: bloggy
      MYSQL_PASSWORD: bloggy
